'use client'

import { SideMenu } from '@/components/SideMenu'
import './globals.css'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Inter, DM_Sans, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] })
const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--menu-font',
})
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--menu-font-sub',
})

export const metadata: Metadata = {
  title: 'Theia',
  description: 'Generated by Theia',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${dmSans.className} ${openSans.className}`}
      >
        <SideMenu>{children}</SideMenu>
      </body>
    </html>
  )
}
